apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-customer
  namespace: yaobank
spec:
  ingressClassName: nginx
  rules:
    - host: www.yaobank.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: customer
                port:
                  number: 80
            path: /
