apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: app.cartservice
  namespace: hipstershop
spec:
  tier: app
  order: 875
  selector: app == "cartservice"
  ingress:
    - action: Allow
      protocol: UDP
      source:
        selector: app == "checkoutservice"||app == "frontend"
      destination:
        ports:
          - "7070"
  egress:
    - action: Allow
      protocol: TCP
      source: {}
      destination:
        selector: app == "redis-cart"
        ports:
          - "6379"
  types:
    - Ingress
    - Egress
