apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: app.paymentservice
  namespace: hipstershop
spec:
  tier: app
  order: 1600
  selector: app == "paymentserviceee"
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app == "checkoutservice"
      destination:
        ports:
          - "50051"
  types:
    - Ingress
